**/bin/
**/obj/
**/.vs/
**/.vscode/
**/.idea/
**/*.user
**/*.suo
**/*.DotSettings.user

.git/
.gitignore

Deployment/Dev/data/
Deployment/Dev/secrets/
Deployment/Dev/certs/
Deployment/Dev/keypair/

**/.env
**/*.log
**/*.tmp
**/*.swp
**/*.db
**/*.sqlite

**/node_modules/
