**/bin/
**/obj/
**/.vs/
**/.vscode/
**/.idea/
**/*.user
**/*.suo
**/*.DotSettings.user

.git/
.gitignore

DevopsTools/Dev/data/
DevopsTools/Dev/secrets/
DevopsTools/Dev/certs/
DevopsTools/Dev/keypair/

**/.env
**/*.log
**/*.tmp
**/*.swp
**/*.db
**/*.sqlite

**/node_modules/
