x-observability-logging: &observability-logging
  driver: json-file
  options:
    max-size: "${DOCKER_LOG_MAX_SIZE}"
    max-file: "${DOCKER_LOG_MAX_FILE}"

x-observability-service: &observability-service
  restart: unless-stopped
  init: true
  user: "${OBSERVABILITY_UID}:${OBSERVABILITY_GID}"
  security_opt:
    - no-new-privileges:true
  logging: *observability-logging

x-keycloak-env: &keycloak-env
  # --- Keycloak Configuration ---
  KC_HTTP_MANAGEMENT_PORT: 9990
  KC_METRICS_ENABLED: true
  KC_HEALTH_ENABLED: true
  KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
  KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
  KC_LOG_LEVEL: "info,org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory:debug"
  KC_CACHE_STACK: "jdbc-ping"
  KC_SPI_STICKY_SESSION_ENCODER__INFINISPAN__SHOULD_ATTACH_ROUTE: true
  # --- HTTP & Host Configuratiown ---
  KC_HOSTNAME: "https://${APP_HOSTNAME}:${GATEWAY_PORT}/auth"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: "xforwarded"
  KC_PROXY: "edge"
  # --- Database Configuration ---
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?sslmode=verify-full&sslrootcert=/opt/keycloak/conf/root.crt&sslcert=/opt/keycloak/conf/server.crt&sslkey=/opt/keycloak/conf/server.key
  KC_DB_USERNAME: ${POSTGRES_USER}
  KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

x-keycloak-command: &keycloak-command
  command: [
    "start",
    "--import-realm",
    "--optimized",
    "--verbose", # may not need in production
    "--cache=ispn"
  ]
  
services:
  backend:
    image: ${NAMESPACE}/${REPOSITORY_NAME}/backend:${BACKEND_TAG}
    container_name: backend
    networks:
      - dev-network
      - dev-observability-network
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Server__Name: "Restaurant_Dev"
      
      # --------- API Documentation ---------
      OpenApi__Title: "Restaurant REST APIs for Development"
      OpenApi__ApiDocs: "restaurant-api-docs-dev-dev"
      OpenApi__Description: "This is the APIs documentation for Restaurant in Development."
      OpenApi__ServerUrl: "https://${APP_HOSTNAME}:${GATEWAY_PORT}/restaurant/api"
      
      # ---------- Observability ---------
      Observability__UseTracingExporter: "otlp"
      Observability__UseMetricsExporter: "otlp"
      Observability__UseLoggingExporter: "otlp"
      Observability__HistogramAggregation: "exponential"
      Observability__Otlp__Endpoint: "http://otel-collector:4317"

  # --------- Envoy ---------
  gateway:
    image: ${ENVOY_REPO_NAME}/envoy:${ENVOY_TAG:-latest}
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:443"
      - "${GATEWAY_ADMIN_PORT}:9001"
    networks:
      - dev-network
      - dev-observability-network
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    volumes:
      - ${SERVICES_DIR}/envoy/gateway.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs/gateway:/etc/envoy/certificates:ro

  # --------- Postgres ---------
  postgres:
    image: ${NAMESPACE}/${REPOSITORY_NAME}/postgres:${POSTGRES_TAG}
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - dev-network
    command: >
      postgres
      -c max_connections=500
      -c config_file=/etc/postgres/postgres.conf
      -c hba_file=/etc/postgres/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    volumes:
      - ${SERVICES_DIR}/postgres/config/postgres.conf:/etc/postgres/postgres.conf:ro
      - ${SERVICES_DIR}/postgres/config/pg_hba.conf:/etc/postgres/pg_hba.conf:ro
      - ${SERVICES_DIR}/postgres/init-db:/docker-entrypoint-initdb.d:ro
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/18/docker

  # --------- Keycloak cluster ---------
  keycloak0:
    image: ${NAMESPACE}/${REPOSITORY_NAME}/keycloak:${KEYCLOAK_TAG}
    container_name: keycloak0
    depends_on:
      postgres:
        condition: service_healthy
#    ports:
#      - "${KEYCLOAK_PORT}:8080" # HTTP
#      - "${KEYCLOAK_MANAGEMENT_PORT}:9990" # Management port
#      - "${KEYCLOAK_JGROUPS_PORT}:7800" # JGroups
    networks:
      - dev-network
    <<: *keycloak-command
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9990; echo -e 'GET /auth/health/ready HTTP/1.1\r\nHost: localhost:9990\r\nConnection: close\r\n\r\n' >&3; cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: always # unless-stopped
    volumes:
      - ${SERVICES_DIR}/keycloak/import:/opt/keycloak/data/import
      - ${SERVICES_DIR}/keycloak/export:/opt/keycloak/data/export
    environment:
      <<: *keycloak-env
      KC_SPI_CACHE_EMBEDDED__DEFAULT__MACHINE_NAME: node0

  # --------- Observability ---------
  loki:
    <<: *observability-service
    image: ${LOKI_REPO_NAME}/loki:${LOKI_TAG}
    container_name: loki
    command: ["-config.file=/etc/loki/loki.yaml"]
#    ports:
#      - "${LOKI_PORT}:3100"
    networks:
      - dev-observability-network
    volumes:
      - ${SERVICES_DIR}/loki/loki.yaml:/etc/loki/loki.yaml:ro
      - ${LOKI_DATA_DIR}:/loki
#    healthcheck:
#      test: ["CMD", "/usr/bin/loki", "-version"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 10s

  tempo:
    <<: *observability-service
    image: ${TEMPO_REPO_NAME}/tempo:${TEMPO_TAG}
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
#    ports:
#      - "${TEMPO_PORT}:3200"
    networks:
      - dev-observability-network
    volumes:
      - ${SERVICES_DIR}/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - ${TEMPO_DATA_DIR}:/var/tempo
    depends_on:
      prometheus:
        condition: service_started
#    healthcheck:
#      test: ["CMD", "/tempo", "-version"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 10s

  otel-collector:
    <<: *observability-service
    image: ${OTEL_REPO_NAME}/opentelemetry-collector-contrib:${OTEL_TAG}
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/otel.yml"]
#    ports:
#      - "${OTEL_COLLECTOR_OTLP_GRPC_PORT}:4317"
#      - "${OTEL_COLLECTOR_OTLP_HTTP_PORT}:4318"
#      - "${OTEL_COLLECTOR_HEALTH_PORT}:13133"
    networks:
      - dev-network
      - dev-observability-network
    volumes:
      - ${SERVICES_DIR}/otel/otel.yml:/etc/otelcol-contrib/otel.yml:ro
    depends_on:
      loki:
        condition: service_started
      tempo:
        condition: service_started
#    healthcheck:
#      test: ["CMD", "/otelcol-contrib", "--version"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 10s

  prometheus:
    <<: *observability-service
    image: ${PROMETHEUS_REPO_NAME}/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}
      - --storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE}
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
#    ports:
#      - "${PROMETHEUS_PORT}:9090"
    networks:
      - dev-observability-network
    volumes:
      - ${SERVICES_DIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${PROMETHEUS_DATA_DIR}:/prometheus
#    healthcheck:
#      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9090/-/healthy"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 15s

  grafana:
    <<: *observability-service
    image: ${GRAFANA_REPO_NAME}/grafana:${GRAFANA_TAG}
    container_name: grafana
#    ports:
#      - "${GRAFANA_PORT}:3000"
    networks:
      - dev-observability-network
    volumes:
      - ${SERVICES_DIR}/grafana/provisioning:/etc/grafana/provisioning:ro
      - ${SERVICES_DIR}/grafana/dashboards:/etc/grafana/dashboards:ro
      - ./certs/ca/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      tempo:
        condition: service_started
    environment:
      GF_SERVER_ROOT_URL: https://${APP_HOSTNAME}:${GATEWAY_PORT}/observability
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_HTTP_PORT: 3000
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_METRICS_ENABLED: "true"
      GF_LOG_MODE: console
#      GF_INSTALL_PLUGINS: ""
#      GF_PLUGINS_PREINSTALL_DISABLED: "true"
#      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
#      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
#    healthcheck:
#      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000/api/health"]
#      interval: 30s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

networks:
  dev-network:
    driver: bridge
  dev-observability-network:
    driver: bridge
