apiVersion: 1

prune: true

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
    version: 2

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 2
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags:
          - key: service.name
            value: service_name
          - key: service.namespace
            value: service_namespace
          - key: deployment.environment.name
            value: deployment_environment_name
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags:
          - key: service.name
            value: service
          - key: service.namespace
            value: service_namespace
          - key: deployment.environment.name
            value: deployment_environment_name
        queries:
          - name: Request rate
            query: sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))
          - name: P95 latency
            query: histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m])) by (le))
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
      spanBar:
        type: Tag
        tag: http.route
      streamingEnabled:
        search: true
        metrics: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 2
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:trace_id|traceId|traceid)["=:\s]+([A-Fa-f0-9]{16,32})'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: View trace
