apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
    
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
    spec:
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      
      containers:
        - name: {{ include "gateway.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toJson .Values.command }}
          
          ports:
            - name: https
              containerPort: {{ .Values.containerPorts.https }}
            - name: admin
              containerPort: {{ .Values.containerPorts.admin }}
              
          volumeMounts:
            - name: gateway-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
            - name: gateway-certs
              mountPath: /etc/envoy/certificates
              readOnly: true
              
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          # production health checks (recommended)
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
              
      volumes:
        - name: gateway-config
          configMap:
            name: {{ include "gateway.configMapName" . }}
            items:
              - key: envoy.yaml
                path: envoy.yaml
                
        - name: gateway-certs
          secret:
            secretName: {{ include "gateway.tlsSecretName" . }}
            
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
