{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.tlsSecretName" . }}
  namespace: {{ include "api-gateway.namespace" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tls.certFileName }}: |-
{{ required "tls.certificate is required when tls.create=true" .Values.tls.certificate | indent 4 }}
  {{ .Values.tls.keyFileName }}: |-
{{ required "tls.privateKey is required when tls.create=true" .Values.tls.privateKey | indent 4 }}
{{- end }}
