apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.containerPorts.https }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.containerPorts.admin }}
