{{- if .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "backend.fullname" .)) .Values.secret.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}