services:
  base-solution:
    container_name: base-solution
    image: base-solution
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60000:60000"
      - "60001:60001"
    volumes:
      - ../..:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

