apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learn-dot-net

resources:
  - k8s/namespace.yaml
  - k8s/backend-deployment.yaml
  - k8s/backend-service.yaml
  - k8s/api-gateway-deployment.yaml
  - k8s/api-gateway-service.yaml

configMapGenerator:
  - name: api-gateway-config
    files:
      - envoy.yaml=envoy/api-gateway.yaml

secretGenerator:
  - name: api-gateway-certs
    files:
      - api-gateway.cert.pem=certs/api-gateway/api-gateway.cert.pem
      - api-gateway.key.pem=certs/api-gateway/api-gateway.key.pem

generatorOptions:
  disableNameSuffixHash: true
