services:
  # --------- Envoy ---------
  backend-gateway:
    image: envoyproxy/envoy:${ENVOY_TAG:-latest}
    container_name: backend-gateway
    ports:
      - "${GATEWAY_PORT}:443"
      - "9901:9901"
    networks:
      - dev-network
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml" ]
    volumes:
      - ./envoy/backend-gateway.yaml:/etc/envoy/envoy.yaml
      - ./certs/backend-gateway:/etc/envoy/certificates
      
  backend:
    image: ${NAMESPACE}/${REPOSITORY_NAME}/backend:${BACKEND_TAG}
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "60001:${BACKEND_CONTAINER_PORT}"  
    networks:
      - dev-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    
networks:
  dev-network:
    driver: bridge

