{{- if .Values.apiGateway.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "learn-dot-net.apiGatewaySecretName" . }}
  namespace: {{ include "learn-dot-net.namespace" . }}
  labels:
    {{- include "learn-dot-net.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
type: Opaque
data:
  {{ .Values.apiGateway.tls.certFileName }}: {{ required "apiGateway.tls.certificate is required when apiGateway.tls.create=true" .Values.apiGateway.tls.certificate | b64enc | quote }}
  {{ .Values.apiGateway.tls.keyFileName }}: {{ required "apiGateway.tls.privateKey is required when apiGateway.tls.create=true" .Values.apiGateway.tls.privateKey | b64enc | quote }}
{{- end }}
