apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "learn-dot-net.apiGatewayConfigName" . }}
  namespace: {{ include "learn-dot-net.namespace" . }}
  labels:
    {{- include "learn-dot-net.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
data:
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.apiGateway.containerPorts.admin }}

    static_resources:
      listeners:
        - name: listener_https
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{ .Values.apiGateway.containerPorts.https }}

          listener_filters:
            - name: envoy.filters.listener.tls_inspector
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector

          filter_chains:
            - filter_chain_match:
                server_names:
                  - {{ .Values.apiGateway.host | quote }}

              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  common_tls_context:
                    tls_certificates:
                      - certificate_chain:
                          filename: /etc/envoy/certificates/{{ .Values.apiGateway.tls.certFileName }}
                        private_key:
                          filename: /etc/envoy/certificates/{{ .Values.apiGateway.tls.keyFileName }}

              filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: AUTO
                    stat_prefix: ingress_http

                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: services
                          domains:
                            - "{{ .Values.apiGateway.host }}:{{ .Values.apiGateway.externalPort }}"

                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: {{ .Values.apiGateway.envoy.clusterName }}

                              request_headers_to_add:
                                - header:
                                    key: x-forwarded-proto
                                    value: https
                                - header:
                                    key: x-forwarded-port
                                    value: "{{ .Values.apiGateway.externalPort }}"

                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: {{ .Values.apiGateway.envoy.clusterName }}
          connect_timeout: {{ .Values.apiGateway.envoy.connectTimeout }}
          type: logical_dns
          lb_policy: round_robin
          dns_lookup_family: {{ .Values.apiGateway.envoy.dnsLookupFamily }}

          load_assignment:
            cluster_name: {{ .Values.apiGateway.envoy.clusterName }}
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ default (include "learn-dot-net.backendName" .) .Values.apiGateway.envoy.backendAddressOverride }}
                        port_value: {{ .Values.backend.service.port }}

          health_checks:
            - timeout: 3s
              interval: 10s
              unhealthy_threshold: 3
              healthy_threshold: 2
              http_health_check:
                path: {{ .Values.apiGateway.envoy.healthCheckPath | quote }}
