apiVersion: v1
kind: Service
metadata:
  name: {{ include "learn-dot-net.backendName" . }}
  namespace: {{ include "learn-dot-net.namespace" . }}
  labels:
    {{- include "learn-dot-net.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "learn-dot-net.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
