{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "learn-dot-net.namespace" . }}
  labels:
    {{- include "learn-dot-net.labels" . | nindent 4 }}
{{- end }}
