namespace:
  create: false
  name: learn-dot-net

backend:
  name: backend
  replicaCount: 1
  image:
    repository: leduynhan1201/learn-dot-net/backend
    tag: "1.0.0"
    pullPolicy: Never
  containerPort: 60001
  service:
    type: ClusterIP
    port: 60001
  env:
    ASPNETCORE_ENVIRONMENT: Development
  resources: {}

apiGateway:
  name: api-gateway
  replicaCount: 1
  host: backend.learn-dot-net.dev
  externalPort: 60000
  image:
    repository: envoyproxy/envoy
    tag: tools-dev
    pullPolicy: IfNotPresent
  command:
    - envoy
    - -c
    - /etc/envoy/envoy.yaml
  containerPorts:
    https: 443
    admin: 9901
  service:
    type: ClusterIP
    httpsPort: 443
    adminPort: 9901
  configMapName: api-gateway-config
  tls:
    create: false
    existingSecret: api-gateway-certs
    certFileName: api-gateway.cert.pem
    keyFileName: api-gateway.key.pem
    certificate: ""
    privateKey: ""
  envoy:
    clusterName: api_gateway
    connectTimeout: 5s
    dnsLookupFamily: V4_ONLY
    healthCheckPath: /health/info
    backendAddressOverride: ""
  resources: {}
