services:
  demo-backend:
    container_name: demo-backend
    image: demo-backend
    build:
      context: .
      dockerfile: API/Docker/Local/Dockerfile
    ports:
      - "60000:60000"  
    volumes:
      - ./API:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

